application:
  subdomain: gopeed
  background_task: true
  multi_instance: true

  upstreams:
    - location: /
      backend: http://gopeed:9999/
services:
  gopeed:
    # liwei2633/gopeed:v1.9.3
    image: registry.lazycat.cloud/czyt/liwei2633/gopeed:05ed0159dea90dcb
    environment:
      - PUID=0
      - PGID=0
      - UMASK=22
    binds:
      - /lzcapp/run/mnt/home/{{.U.download_dir_name}}:/app/Downloads
      - /lzcapp/var/storage:/app/storage

ext_config:
  enable_document_access: true
  enable_media_access: true
