lzc-sdk-version: "0.1"
name: Gopeed够快下载器
package: cloud.lazycat.app.gopeed
version: 1.6.8
description: 一款现代化的下载器
homepage: https://gopeed.com
author: GopeedLab
application:
  subdomain: gopeed
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://gopeed.cloud.lazycat.app.gopeed.lzcapp:9999/
services:
  gopeed:
    image: registry.lazycat.cloud/czyt/liwei2633/gopeed:53080d4adb3ba9f1
    environment:
      - PUID=0
      - PGID=0
      - UMASK=22
    binds:
      - /lzcapp/var/Downloads:/app/Downloads
      - /lzcapp/var/storage:/app/storage
